### ISSUE TITLE
Game Crashes :(

### ISSUE THREAD

**Issue by Fou-dou** [Brotenko/PMMasterQuest#1]
Hello, I'm currently playing Paper Mario Master Quest Jr. on Bizhawk and when I get to the credit, my game crashes. I think it happens when I see the Mecha Bowser with the Koopa Bros on top.

**Comment by zathx** [comment]
Similar issue here on the normal Master Quest non-Jr.

**Comment by Brotenko** [comment]
A known issue that will be fixed in the next version - Sorry for the inconvenience.
