### ISSUE TITLE
Game Freeze in Tubba Blubba's Castle

### ISSUE THREAD

**Issue by doodleintime** [Brotenko/PMMasterQuest#10]
So for some reason when I spend around five minutes in Tubba Blubba's castle going around and doing stuff, the game will freeze. I have tested this on the latest development version of Project 64 with GlideN64 and Azimer's HLE audio v0.70 WIP 10, and on Mupen64Plus with GlideN64 and ParaLLEI N64 (on the RetroArch frontend), and the freeze happens on all three cases. I will be posting a .zip with two versions of the save I have been using on all three cases, one for for project 64. and another for Mupen64Plus, because that might help find the problem. One more thing I have to say is that this is not on the Jr. version of Master Quest, it is for the normal version.

[master quest crash save.zip](https://github.com/Brotenko/PMMasterQuest/files/6330466/master.quest.crash.save.zip)

**Comment by Brotenko** [comment]
Should be resolved in newest release.
