### ISSUE TITLE
Cannot get beyond scripted fight at beginning of game?

### ISSUE THREAD

**Issue by Dokunite** [Brotenko/PMMasterQuest#15]
Can't seem to get beyond the first fight with Bowser, game offers to restart battle, reload from save block or load file select after Bowser reduces your HP to 0. Seems like it's treating the Bowser fight like it would a normal battle?

**Comment by gamezoid123** [comment]
Hey, it looks like you were able to get past this point. What ended up being the solution? I'm stuck at this fight and a little confused.
