### ISSUE TITLE
General guy crashes game

### ISSUE THREAD

**Issue by theKidOfArcrania** [Brotenko/PMMasterQuest#16]
When general guy (I believe) is trying to throw a bomb, the games just crashes with invalid address load/TLB. ~~(This is for PMMQ Jr btw, but I would guess this would also apply for PMMQ?)~~ EDIT: PMMQ works fine

I know it's probably old and unsupported so if that's the case, I'll probably just do some more reverse engineering of the PMMQ patch code of this to try to fix it myself.

Step before crash:
![Step before crash](https://user-images.githubusercontent.com/12724920/181484156-85de5fcb-f9f1-47b7-8559-efa6902020c1.png)

Step after crash: [1]
![Step after crash](https://user-images.githubusercontent.com/12724920/181484215-6b9c3e6f-5855-4689-a514-cb260e139535.png)

Diagnosing the issue a bit more carefully it seems like the script for throwing a bomb[2] seems to summon an enemy[3] from variable slot 0 with a formation that seems to be pointing an invalid actor blueprint[4] As soon as the game tries to create the actor and load the script, we reach the unexpected crash resulting with an address read at address 0x7, resulting in a TLB miss exception.

Notes:
1. Error message might look different because I originally attempted to patch out TLB exception initially to see if that would resolve the issue.
2. Not sure if this is actually the attack_throw_bomb script (but just saw the first two instructions matching that one).
3. Not sure if you were suppose to summon an enemy at this step (original code just seems to proceed to animate bomb throw) and does not call SummonEnemy at all
4. Maybe the patch somehow didn't change the actor blueprint or the pointer is just wrong?

**Comment by theKidOfArcrania** [comment]
Resolved in new version (1.5.1.2)

**Comment by aj-n** [comment]
Where can one find version 1.5.1.2?

My 1.5.1.1 version is currently also stuck at the General guy fight. Every time he first pops out of the tank, the game freezes.

**Comment by theKidOfArcrania** [comment]
Hi, the most up-to-date version should also be merged back onto the repo.
