### ISSUE TITLE
Game Crashes At Credits D:

### ISSUE THREAD

**Issue by zathx** [Brotenko/PMMasterQuest#2]
Please help, my friend and I are playing through Master Quest and we just defeated Bowser and can't get past the credits D:

We spent over 60 hours (no savestates/rewinds/cheats) on this file so any help is appreciated, we are loving master quest and really wish to finish it.

Rom File: Paper Mario Master Quest 1.3.0.2.z64 (Normal, not Jr.)
Save File Attached: [Paper Mario Master Quest 1.3.0.2.SaveRAM](https://drive.google.com/file/d/1A6QznJ96JxlfKClYhKppyFJcptcSbVDE/view?usp=sharing)
Using Bizhawk with recommended settings. Tried on 3 different PC's.

Game crashes after defeating Bowser during credits, near Chuck Quizmo/The 3 Female Toads/Mechabowser. We changed the video plugin to Rice and managed to get past this part, but then it crashed at the Toads With Glowing Spots.

Error Screen: https://i.imgur.com/PEyprkK.png

Thank you so, so much.

**Comment by bkimmett** [comment]
It's a known bug. Sadly, it's due to the rom running out of memory, and not your emulator settings; so, there's nothing you can do to fix it. 

It's fixed in the upcoming version.

**Comment by Brotenko** [comment]
A known issue that will be fixed in the next version - Sorry for the inconvenience.
