### ISSUE TITLE
Electro Blooper Crash Game (Equipped Zap Tap Badge)

### ISSUE THREAD

**Issue by Pikachujones** [Brotenko/PMMasterQuest#3]
When I can get equip with Zap Tap then battle with Electro Blooper, however there two problem... One of blooper baby can leech it while shocked and still there repeat "A" button due I didn't use repeat "A" then Electro Blooper going attack with Ink Shot (I believe AI used) then Crash Game with code list.  Now second problem I had used hammer throw attack blooper baby get one shot then electro blooper get attack me then back to place and game is gonna stopped now.  That's all for report bug, so now I'm gonna fight electro blooper without zap tap. -sigh-

**Comment by Brotenko** [comment]
A known issue that will be fixed in the next version - Sorry for the inconvenience.
