### ISSUE TITLE
Game crash in Koopa Village

### ISSUE THREAD

**Issue by shibatan** [Brotenko/PMMasterQuest#5]
When visiting Koopa Village while the Bob-ombs are arguing inside, if you change partners to Bombette _anywhere on that map_, the game will encounter an error and crash. This does not happen in the other map of Koopa Village. 

[Image of the error here.](https://i.imgur.com/hMmxNlG.png)

**Comment by Brotenko** [comment]
A known issue that will be fixed in the next version - Sorry for the inconvenience.
The issue has to do with complex 3D structures (GeneralGuy tank, Koopa Village houses, etc) and can happen everywhere where these complex structures are loaded.
