### ISSUE TITLE
Tasty Tonic effect is changed ?

### ISSUE THREAD

**Issue by Atralb** [Brotenko/PMMasterQuest#8]
I just realized tasty tonic's description has been changed, and I used one outside of battle that healed me for 99 hearts (and apparently also leaves me with only 1 FP). Is this a change made by you or in the Pro Mode ?

If it has been changed by you, it is not listed in your readme. If not, do you know where I could get the list of changes not directly made by you but still transfered within PM Master Quest ?

Thanks

**Comment by Brotenko** [comment]
The MQ dev team made that change, yes.
The changelog is only for the update to 1.3, not for everything that has been done. There's no changelog for everything tho, only this one.
