### ISSUE TITLE
Softlock in Shyguys Toybox

### ISSUE THREAD

**Issue by SiriusDarkblaze** [Brotenko/PMMasterQuest#9]
When moving through the toybox after the pink station to the pink switch in the area before the switch with the flame guy behind the blocks if you run in front of the blocks you get pushed onto the train tracks and soft locked. I was playing on Openemu for macOS. This was in MQ Jr but probably is in both if that particular area is the same.

![image](https://user-images.githubusercontent.com/81454186/112707888-0b851e00-8e85-11eb-99ed-7b81f5fcb63d.jpg)
Picture for reference attached.

**Comment by Brotenko** [comment]
Hey,

this is a known issue, that won't be fixed. The official support for the hack has been depricated, but feel free to join the Discord as one of the community members picked it back up and is currently continuning development on their own.
